### ISSUE TITLE
Compiler Errors in Unity 2021.3 after updating to 0.2.1

### ISSUE THREAD

**Issue by tftbass78** [Luca3317/TMPEffects#35]
After updating TMPEffects from version 0.1.4 to version 0.2.1 in a Unity project using Unity 2021.3.26f1, new compiler errors appeared. These errors do not appear in Unity 6.

There were 4 compiler errors:
1. Library\PackageCache\com.luca3317.tmpeffects@eab5b48302\Runtime\Effects\TMPAnimations\AnimationCurveUtility.cs(19,22): error CS1061: 'AnimationCurve' does not contain a definition for 'CopyFrom' and no accessible extension method 'CopyFrom' accepting a first argument of type 'AnimationCurve' could be found

     Checking the Unity documentation. it looks like the CopyFrom function was added in Unity 2022, so it isn't available in 2021. After commenting out this line, a few more errors popped up. https://docs.unity3d.com/6000.0/Documentation/ScriptReference/AnimationCurve.CopyFrom.html

2.  Library\PackageCache\com.luca3317.tmpeffects@eab5b48302\Editor\GenericAnimation\GenericAnimationEditor.cs(297,41): error CS0117: 'ReorderableList' does not contain a definition for 'GetReorderableListFromSerializedProperty'

    This error also appears on line 304 of the same script

3. Library\PackageCache\com.luca3317.tmpeffects@eab5b48302\Editor\TMPKeywordDatabaseEditor.cs(58,13): error CS7036: There is no argument given that corresponds to the required formal parameter 'curves' of 'TMPKeywordDatabaseEditor.ResetAnimationCurves(SerializedProperty, IDictionary<string, AnimationCurve>)'

4. Library\PackageCache\com.luca3317.tmpeffects@eab5b48302\Editor\TMPKeywordDatabaseEditor.cs(305,59): error CS0246: The type or namespace name 'ParameterTypes' could not be found (are you missing a using directive or an assembly reference?)

Commenting out the problematic lines allows the code to compile, with basic functionality of TMPEffects still intact.

**Comment by Luca3317** [comment]
Hey, the branch I linked should have all these things fixed (though Ill still have to do some more testing concerning the GenericAnimation ReorderableLists) and Ill merge it into main in the next few days. If these errors are blocking you from working on your project just use the version on that branch in the meantime

I wont close yet in case my testing shows the solution isnt fully working yet
